[build-system]
requires = ["flit_core >=3.0.0,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module="flit"
author="Thomas Kluyver"
author-email="thomas@kluyver.me.uk"
home-page="https://github.com/takluyver/flit"
requires=[
    "flit_core>=3.0.0",
    "requests",
    "docutils",
    "pytoml",
    "zipfile36; python_version in '3.3 3.4 3.5'",
]
requires-python=">=3.5"
description-file="README.rst"
classifiers=["Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.flit.metadata.requires-extra]
test = [
	"testpath",
	"responses",
	"pytest>=2.7.3",
	"pytest-cov",
]
doc = [
	"sphinx",
	"sphinxcontrib_github_alt",
	"pygments-github-lexers",  # TOML highlighting
]

[tool.flit.metadata.urls]
Documentation = "https://flit.readthedocs.io/en/latest/"

[tool.flit.scripts]
flit = "flit:main"
