[build-system]
requires = ["flit"]
build_backend = "flit.buildapi"

[tool.flit.metadata]
module="flit"
author="Thomas Kluyver"
author-email="thomas@kluyver.me.uk"
home-page="https://github.com/takluyver/flit"
requires=["requests",
    "docutils",
    "requests_download",
    "pytoml",
]
requires-python="3"
description-file="README.rst"
classifiers=["Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.flit.scripts]
flit = "flit:main"
